[phases.setup]
nixPkgs = ["php83", "php83Extensions.pdo_mysql", "php83Extensions.mysqli", "php83Extensions.mbstring"]

[phases.install]
cmds = ["composer install --no-dev --optimize-autoloader || true"]

[start]
cmd = "php -S 0.0.0.0:$PORT -t pages"